[Fri Apr 05 15:45:45 2013] [error] [client 127.0.0.1] File does not exist: /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/favicon.ico
[Fri Apr 05 15:45:51 2013] [error] [client 127.0.0.1] File does not exist: /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/favicon.ico
[Fri Apr 05 15:45:59 2013] [error] [client 127.0.0.1] PHP Fatal error:  Cannot use Symfony\\Component\\Routing\\RequestContext as RequestContext because the name is already in use in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/LazyUrlMatcher.php on line 14, referer: http://oauth.dev/
[Fri Apr 05 15:45:59 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauth.dev/
[Fri Apr 05 15:45:59 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:0, referer: http://oauth.dev/
[Fri Apr 05 15:45:59 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:61, referer: http://oauth.dev/
[Fri Apr 05 15:45:59 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:481, referer: http://oauth.dev/
[Fri Apr 05 15:45:59 2013] [error] [client 127.0.0.1] PHP   4. Silex\\Application->boot() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:495, referer: http://oauth.dev/
[Fri Apr 05 15:45:59 2013] [error] [client 127.0.0.1] PHP   5. Silex\\Provider\\SessionServiceProvider->boot() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:179, referer: http://oauth.dev/
[Fri Apr 05 15:45:59 2013] [error] [client 127.0.0.1] PHP   6. Pimple->offsetGet() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:118, referer: http://oauth.dev/
[Fri Apr 05 15:45:59 2013] [error] [client 127.0.0.1] PHP   7. Pimple::{closure:/home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:118-126}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:83, referer: http://oauth.dev/
[Fri Apr 05 15:45:59 2013] [error] [client 127.0.0.1] PHP   8. Silex\\Application->Silex\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:122, referer: http://oauth.dev/
[Fri Apr 05 15:45:59 2013] [error] [client 127.0.0.1] PHP   9. Composer\\Autoload\\ClassLoader->loadClass() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:0, referer: http://oauth.dev/
[Fri Apr 05 15:45:59 2013] [error] [client 127.0.0.1] File does not exist: /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/favicon.ico
[Fri Apr 05 15:46:12 2013] [error] [client 127.0.0.1] PHP Fatal error:  Cannot use Symfony\\Component\\Routing\\RequestContext as RequestContext because the name is already in use in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/LazyUrlMatcher.php on line 14, referer: http://oauth.dev/
[Fri Apr 05 15:46:12 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauth.dev/
[Fri Apr 05 15:46:12 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:0, referer: http://oauth.dev/
[Fri Apr 05 15:46:12 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:61, referer: http://oauth.dev/
[Fri Apr 05 15:46:12 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:481, referer: http://oauth.dev/
[Fri Apr 05 15:46:12 2013] [error] [client 127.0.0.1] PHP   4. Silex\\Application->boot() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:495, referer: http://oauth.dev/
[Fri Apr 05 15:46:12 2013] [error] [client 127.0.0.1] PHP   5. Silex\\Provider\\SessionServiceProvider->boot() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:179, referer: http://oauth.dev/
[Fri Apr 05 15:46:12 2013] [error] [client 127.0.0.1] PHP   6. Pimple->offsetGet() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:118, referer: http://oauth.dev/
[Fri Apr 05 15:46:12 2013] [error] [client 127.0.0.1] PHP   7. Pimple::{closure:/home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:118-126}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:83, referer: http://oauth.dev/
[Fri Apr 05 15:46:12 2013] [error] [client 127.0.0.1] PHP   8. Silex\\Application->Silex\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:122, referer: http://oauth.dev/
[Fri Apr 05 15:46:12 2013] [error] [client 127.0.0.1] PHP   9. Composer\\Autoload\\ClassLoader->loadClass() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:0, referer: http://oauth.dev/
[Fri Apr 05 15:46:12 2013] [error] [client 127.0.0.1] File does not exist: /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/favicon.ico
[Fri Apr 05 15:47:59 2013] [error] [client 127.0.0.1] PHP Fatal error:  Cannot use Symfony\\Component\\Routing\\RequestContext as RequestContext because the name is already in use in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/LazyUrlMatcher.php on line 14, referer: http://oauth.dev/
[Fri Apr 05 15:47:59 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauth.dev/
[Fri Apr 05 15:47:59 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:0, referer: http://oauth.dev/
[Fri Apr 05 15:47:59 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:61, referer: http://oauth.dev/
[Fri Apr 05 15:47:59 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:481, referer: http://oauth.dev/
[Fri Apr 05 15:47:59 2013] [error] [client 127.0.0.1] PHP   4. Silex\\Application->boot() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:495, referer: http://oauth.dev/
[Fri Apr 05 15:47:59 2013] [error] [client 127.0.0.1] PHP   5. Silex\\Provider\\SessionServiceProvider->boot() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:179, referer: http://oauth.dev/
[Fri Apr 05 15:47:59 2013] [error] [client 127.0.0.1] PHP   6. Pimple->offsetGet() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:118, referer: http://oauth.dev/
[Fri Apr 05 15:47:59 2013] [error] [client 127.0.0.1] PHP   7. Pimple::{closure:/home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:118-126}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:83, referer: http://oauth.dev/
[Fri Apr 05 15:47:59 2013] [error] [client 127.0.0.1] PHP   8. Silex\\Application->Silex\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:122, referer: http://oauth.dev/
[Fri Apr 05 15:47:59 2013] [error] [client 127.0.0.1] PHP   9. Composer\\Autoload\\ClassLoader->loadClass() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:0, referer: http://oauth.dev/
[Fri Apr 05 15:47:59 2013] [error] [client 127.0.0.1] File does not exist: /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/favicon.ico
[Fri Apr 05 16:03:08 2013] [error] [client 127.0.0.1] File does not exist: /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/favicon.ico
[Fri Apr 05 16:03:13 2013] [error] [client 127.0.0.1] File does not exist: /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/favicon.ico
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP Fatal error:  Cannot use Symfony\\Component\\Routing\\RequestContext as RequestContext because the name is already in use in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/LazyUrlMatcher.php on line 14
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP Stack trace:
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:0
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:61
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:481
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP   4. Silex\\Application->boot() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:495
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP   5. Silex\\Provider\\SessionServiceProvider->boot() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:179
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP   6. Pimple->offsetGet() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:118
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP   7. Pimple::{closure:/home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:118-126}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:83
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP   8. Silex\\Application->Silex\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:122
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP   9. Composer\\Autoload\\ClassLoader->loadClass() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:0
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP Fatal error:  Cannot use Symfony\\Component\\Routing\\RequestContext as RequestContext because the name is already in use in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/LazyUrlMatcher.php on line 14
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP Stack trace:
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:0
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:61
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:481
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP   4. Silex\\Application->boot() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:495
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP   5. Silex\\Provider\\SessionServiceProvider->boot() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:179
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP   6. Pimple->offsetGet() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:118
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP   7. Pimple::{closure:/home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:118-126}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:83
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP   8. Silex\\Application->Silex\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:122
[Fri Apr 05 16:03:51 2013] [error] [client 127.0.0.1] PHP   9. Composer\\Autoload\\ClassLoader->loadClass() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:0
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP Fatal error:  Cannot use Symfony\\Component\\Routing\\RequestContext as RequestContext because the name is already in use in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/LazyUrlMatcher.php on line 14
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP Stack trace:
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:0
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:61
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:481
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP   4. Silex\\Application->boot() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:495
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP   5. Silex\\Provider\\SessionServiceProvider->boot() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:179
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP   6. Pimple->offsetGet() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:118
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP   7. Pimple::{closure:/home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:118-126}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:83
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP   8. Silex\\Application->Silex\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:122
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP   9. Composer\\Autoload\\ClassLoader->loadClass() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:0
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP Fatal error:  Cannot use Symfony\\Component\\Routing\\RequestContext as RequestContext because the name is already in use in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/LazyUrlMatcher.php on line 14
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP Stack trace:
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:0
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:61
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:481
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP   4. Silex\\Application->boot() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:495
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP   5. Silex\\Provider\\SessionServiceProvider->boot() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:179
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP   6. Pimple->offsetGet() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:118
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP   7. Pimple::{closure:/home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:118-126}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:83
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP   8. Silex\\Application->Silex\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:122
[Fri Apr 05 16:03:57 2013] [error] [client 127.0.0.1] PHP   9. Composer\\Autoload\\ClassLoader->loadClass() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php:0
[Fri Apr 05 18:01:12 2013] [error] [client 127.0.0.1] File does not exist: /home/philippe/dev/gitcortext/examples
[Fri Apr 05 18:01:12 2013] [error] [client 127.0.0.1] File does not exist: /home/philippe/dev/gitcortext/examples
[Fri Apr 05 18:01:16 2013] [error] [client 127.0.0.1] File does not exist: /home/philippe/dev/gitcortext/examples
[Fri Apr 05 18:01:16 2013] [error] [client 127.0.0.1] File does not exist: /home/philippe/dev/gitcortext/examples
[Fri Apr 05 18:02:13 2013] [error] [client 127.0.0.1] File does not exist: /home/philippe/dev/gitcortext/examples
[Fri Apr 05 18:02:13 2013] [error] [client 127.0.0.1] File does not exist: /home/philippe/dev/gitcortext/examples
[Fri Apr 05 18:02:15 2013] [error] [client 127.0.0.1] File does not exist: /home/philippe/dev/gitcortext/examples
[Fri Apr 05 18:02:15 2013] [error] [client 127.0.0.1] File does not exist: /home/philippe/dev/gitcortext/examples
[Fri Apr 05 18:02:21 2013] [error] [client 127.0.0.1] File does not exist: /home/philippe/dev/gitcortext/examples
[Fri Apr 05 18:02:22 2013] [error] [client 127.0.0.1] File does not exist: /home/philippe/dev/gitcortext/examples
[Fri Apr 05 18:02:33 2013] [error] [client 127.0.0.1] File does not exist: /home/philippe/dev/gitcortext/examples
[Fri Apr 05 18:02:33 2013] [error] [client 127.0.0.1] File does not exist: /home/philippe/dev/gitcortext/examples
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Notice:  Use of undefined constant CURLOPT_POST - assumed 'CURLOPT_POST' in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/Curl.php on line 39, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:0, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:61, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:481, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:504, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   5. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:73, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   6. call_user_func_array() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   7. Demo\\ControllerProvider->Demo\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   8. Demo\\Curl->request() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/ControllerProvider.php:44, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Notice:  Use of undefined constant CURLOPT_POSTFIELDS - assumed 'CURLOPT_POSTFIELDS' in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/Curl.php on line 62, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:0, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:61, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:481, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:504, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   5. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:73, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   6. call_user_func_array() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   7. Demo\\ControllerProvider->Demo\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   8. Demo\\Curl->request() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/ControllerProvider.php:44, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Notice:  Use of undefined constant CURLOPT_URL - assumed 'CURLOPT_URL' in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/Curl.php on line 77, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:0, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:61, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:481, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:504, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   5. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:73, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   6. call_user_func_array() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   7. Demo\\ControllerProvider->Demo\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   8. Demo\\Curl->request() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/ControllerProvider.php:44, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Notice:  Use of undefined constant CURLOPT_PORT - assumed 'CURLOPT_PORT' in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/Curl.php on line 78, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:0, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:61, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:481, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:504, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   5. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:73, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   6. call_user_func_array() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   7. Demo\\ControllerProvider->Demo\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   8. Demo\\Curl->request() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/ControllerProvider.php:44, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Notice:  Use of undefined constant CURLOPT_USERAGENT - assumed 'CURLOPT_USERAGENT' in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/Curl.php on line 79, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:0, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:61, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:481, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:504, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   5. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:73, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   6. call_user_func_array() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   7. Demo\\ControllerProvider->Demo\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   8. Demo\\Curl->request() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/ControllerProvider.php:44, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Notice:  Use of undefined constant CURLOPT_RETURNTRANSFER - assumed 'CURLOPT_RETURNTRANSFER' in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/Curl.php on line 80, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:0, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:61, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:481, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:504, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   5. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:73, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   6. call_user_func_array() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   7. Demo\\ControllerProvider->Demo\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   8. Demo\\Curl->request() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/ControllerProvider.php:44, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Notice:  Use of undefined constant CURLOPT_TIMEOUT - assumed 'CURLOPT_TIMEOUT' in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/Curl.php on line 81, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:0, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:61, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:481, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:504, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   5. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:73, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   6. call_user_func_array() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   7. Demo\\ControllerProvider->Demo\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   8. Demo\\Curl->request() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/ControllerProvider.php:44, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Notice:  Use of undefined constant CURLOPT_HTTPHEADER - assumed 'CURLOPT_HTTPHEADER' in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/Curl.php on line 82, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:0, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:61, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:481, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:504, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   5. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:73, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   6. call_user_func_array() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   7. Demo\\ControllerProvider->Demo\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   8. Demo\\Curl->request() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/ControllerProvider.php:44, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Notice:  Use of undefined constant CURLOPT_SSL_VERIFYPEER - assumed 'CURLOPT_SSL_VERIFYPEER' in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/Curl.php on line 83, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:0, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:61, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:481, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:504, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   5. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:73, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   6. call_user_func_array() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   7. Demo\\ControllerProvider->Demo\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   8. Demo\\Curl->request() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/ControllerProvider.php:44, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Notice:  Use of undefined constant CURLOPT_FOLLOWLOCATION - assumed 'CURLOPT_FOLLOWLOCATION' in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/Curl.php on line 87, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:0, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:61, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:481, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:504, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   5. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:73, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   6. call_user_func_array() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   7. Demo\\ControllerProvider->Demo\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   8. Demo\\Curl->request() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/ControllerProvider.php:44, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Fatal error:  Call to undefined function Demo\\curl_init() in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/Curl.php on line 120, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:0, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php:61, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:481, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:504, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   5. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:73, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   6. call_user_func_array() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   7. Demo\\ControllerProvider->Demo\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   8. Demo\\Curl->request() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/ControllerProvider.php:44, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 18:08:18 2013] [error] [client 127.0.0.1] PHP   9. Demo\\Curl->doCurlCall() /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/Demo/Curl.php:98, referer: http://oauth.dev/lockdin/authorize?response_type=code&client_id=demoapp&redirect_uri=http%3A%2F%2Foauth.dev%2Fdemo%2Fauthorized
[Fri Apr 05 19:18:05 2013] [error] [client 127.0.0.1] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Accessed request service outside of request scope. Try moving that call to a before handler or controller.' in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:132\nStack trace:\n#0 /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php(83): Silex\\Application->Silex\\{closure}(Object(Silex\\Application))\n#1 /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/LockdIn/ControllerProvider.php(16): Pimple->offsetGet('request')\n#2 /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php(458): LockdIn\\ControllerProvider->connect(Object(Silex\\Application))\n#3 /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php(52): Silex\\Application->mount('/lockdin', Object(LockdIn\\ControllerProvider))\n#4 {main} in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php on line 132
[Fri Apr 05 19:18:05 2013] [error] [client 127.0.0.1] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Accessed request service outside of request scope. Try moving that call to a before handler or controller.' in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:132\nStack trace:\n#0 /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php(83): Silex\\Application->Silex\\{closure}(Object(Silex\\Application))\n#1 /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/LockdIn/ControllerProvider.php(16): Pimple->offsetGet('request')\n#2 /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php(458): LockdIn\\ControllerProvider->connect(Object(Silex\\Application))\n#3 /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php(52): Silex\\Application->mount('/lockdin', Object(LockdIn\\ControllerProvider))\n#4 {main} in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php on line 132
[Fri Apr 05 19:18:15 2013] [error] [client 127.0.0.1] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Accessed request service outside of request scope. Try moving that call to a before handler or controller.' in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:132\nStack trace:\n#0 /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php(83): Silex\\Application->Silex\\{closure}(Object(Silex\\Application))\n#1 /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/LockdIn/ControllerProvider.php(16): Pimple->offsetGet('request')\n#2 /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php(458): LockdIn\\ControllerProvider->connect(Object(Silex\\Application))\n#3 /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php(52): Silex\\Application->mount('/lockdin', Object(LockdIn\\ControllerProvider))\n#4 {main} in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php on line 132
[Fri Apr 05 19:18:15 2013] [error] [client 127.0.0.1] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Accessed request service outside of request scope. Try moving that call to a before handler or controller.' in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php:132\nStack trace:\n#0 /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/pimple/pimple/lib/Pimple.php(83): Silex\\Application->Silex\\{closure}(Object(Silex\\Application))\n#1 /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/src/LockdIn/ControllerProvider.php(16): Pimple->offsetGet('request')\n#2 /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php(458): LockdIn\\ControllerProvider->connect(Object(Silex\\Application))\n#3 /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/web/index.php(52): Silex\\Application->mount('/lockdin', Object(LockdIn\\ControllerProvider))\n#4 {main} in /home/philippe/dev/gitcortext/cortext-auth/examples/bshaffer/oauth2-server-demo/vendor/silex/silex/src/Silex/Application.php on line 132
[Mon Apr 08 19:47:33 2013] [error] [client 127.0.0.1] PHP Fatal error:  Class 'Demo\\Twig\\JsonStringifyExtension' not found in /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php on line 12, referer: http://oauthcli.dev/
[Mon Apr 08 19:47:33 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauthcli.dev/
[Mon Apr 08 19:47:33 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:0, referer: http://oauthcli.dev/
[Mon Apr 08 19:48:30 2013] [error] [client 127.0.0.1] PHP Fatal error:  Class 'Demo\\Twig\\JsonStringifyExtension' not found in /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php on line 12, referer: http://oauthcli.dev/
[Mon Apr 08 19:48:30 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauthcli.dev/
[Mon Apr 08 19:48:30 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:0, referer: http://oauthcli.dev/
[Mon Apr 08 19:48:30 2013] [error] [client 127.0.0.1] PHP Fatal error:  Class 'Demo\\Twig\\JsonStringifyExtension' not found in /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php on line 12
[Mon Apr 08 19:48:30 2013] [error] [client 127.0.0.1] PHP Stack trace:
[Mon Apr 08 19:48:30 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:0
[Mon Apr 08 19:50:02 2013] [error] [client 127.0.0.1] PHP Catchable fatal error:  Argument 1 passed to OAuth2\\HttpFoundationBridge\\Server::createResponse() must be an instance of OAuth2_Response, null given, called in /home/philippe/dev/gitcortext/cortext-auth/server/vendor/bshaffer/oauth2-server-httpfoundation-bridge/src/OAuth2/HttpFoundationBridge/Server.php on line 26 and defined in /home/philippe/dev/gitcortext/cortext-auth/server/vendor/bshaffer/oauth2-server-httpfoundation-bridge/src/OAuth2/HttpFoundationBridge/Server.php on line 29, referer: http://oauthcli.dev/
[Mon Apr 08 19:50:02 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauthcli.dev/
[Mon Apr 08 19:50:02 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:0, referer: http://oauthcli.dev/
[Mon Apr 08 19:50:02 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:62, referer: http://oauthcli.dev/
[Mon Apr 08 19:50:02 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/silex/silex/src/Silex/Application.php:481, referer: http://oauthcli.dev/
[Mon Apr 08 19:50:02 2013] [error] [client 127.0.0.1] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/silex/silex/src/Silex/Application.php:504, referer: http://oauthcli.dev/
[Mon Apr 08 19:50:02 2013] [error] [client 127.0.0.1] PHP   5. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:73, referer: http://oauthcli.dev/
[Mon Apr 08 19:50:02 2013] [error] [client 127.0.0.1] PHP   6. call_user_func_array() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauthcli.dev/
[Mon Apr 08 19:50:02 2013] [error] [client 127.0.0.1] PHP   7. Ctoauth\\ControllerProvider->Ctoauth\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauthcli.dev/
[Mon Apr 08 19:50:02 2013] [error] [client 127.0.0.1] PHP   8. OAuth2\\HttpFoundationBridge\\Server->getResponse() /home/philippe/dev/gitcortext/cortext-auth/server/src/Ctoauth/ControllerProvider.php:20, referer: http://oauthcli.dev/
[Mon Apr 08 19:50:02 2013] [error] [client 127.0.0.1] PHP   9. OAuth2\\HttpFoundationBridge\\Server->createResponse() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/bshaffer/oauth2-server-httpfoundation-bridge/src/OAuth2/HttpFoundationBridge/Server.php:26, referer: http://oauthcli.dev/
[Mon Apr 08 19:52:23 2013] [error] [client 127.0.0.1] PHP Catchable fatal error:  Argument 1 passed to OAuth2\\HttpFoundationBridge\\Server::createResponse() must be an instance of OAuth2_Response, null given, called in /home/philippe/dev/gitcortext/cortext-auth/server/vendor/bshaffer/oauth2-server-httpfoundation-bridge/src/OAuth2/HttpFoundationBridge/Server.php on line 26 and defined in /home/philippe/dev/gitcortext/cortext-auth/server/vendor/bshaffer/oauth2-server-httpfoundation-bridge/src/OAuth2/HttpFoundationBridge/Server.php on line 29, referer: http://oauthcli.dev/
[Mon Apr 08 19:52:23 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauthcli.dev/
[Mon Apr 08 19:52:23 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:0, referer: http://oauthcli.dev/
[Mon Apr 08 19:52:23 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:62, referer: http://oauthcli.dev/
[Mon Apr 08 19:52:23 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/silex/silex/src/Silex/Application.php:481, referer: http://oauthcli.dev/
[Mon Apr 08 19:52:23 2013] [error] [client 127.0.0.1] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/silex/silex/src/Silex/Application.php:504, referer: http://oauthcli.dev/
[Mon Apr 08 19:52:23 2013] [error] [client 127.0.0.1] PHP   5. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:73, referer: http://oauthcli.dev/
[Mon Apr 08 19:52:23 2013] [error] [client 127.0.0.1] PHP   6. call_user_func_array() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauthcli.dev/
[Mon Apr 08 19:52:23 2013] [error] [client 127.0.0.1] PHP   7. Ctoauth\\ControllerProvider->Ctoauth\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauthcli.dev/
[Mon Apr 08 19:52:23 2013] [error] [client 127.0.0.1] PHP   8. OAuth2\\HttpFoundationBridge\\Server->getResponse() /home/philippe/dev/gitcortext/cortext-auth/server/src/Ctoauth/ControllerProvider.php:20, referer: http://oauthcli.dev/
[Mon Apr 08 19:52:23 2013] [error] [client 127.0.0.1] PHP   9. OAuth2\\HttpFoundationBridge\\Server->createResponse() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/bshaffer/oauth2-server-httpfoundation-bridge/src/OAuth2/HttpFoundationBridge/Server.php:26, referer: http://oauthcli.dev/
[Mon Apr 08 19:59:24 2013] [error] [client 127.0.0.1] PHP Catchable fatal error:  Argument 1 passed to OAuth2\\HttpFoundationBridge\\Server::createResponse() must be an instance of OAuth2_Response, null given, called in /home/philippe/dev/gitcortext/cortext-auth/server/vendor/bshaffer/oauth2-server-httpfoundation-bridge/src/OAuth2/HttpFoundationBridge/Server.php on line 26 and defined in /home/philippe/dev/gitcortext/cortext-auth/server/vendor/bshaffer/oauth2-server-httpfoundation-bridge/src/OAuth2/HttpFoundationBridge/Server.php on line 29, referer: http://oauthcli.dev/
[Mon Apr 08 19:59:24 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauthcli.dev/
[Mon Apr 08 19:59:24 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:0, referer: http://oauthcli.dev/
[Mon Apr 08 19:59:24 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:62, referer: http://oauthcli.dev/
[Mon Apr 08 19:59:24 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/silex/silex/src/Silex/Application.php:481, referer: http://oauthcli.dev/
[Mon Apr 08 19:59:24 2013] [error] [client 127.0.0.1] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/silex/silex/src/Silex/Application.php:504, referer: http://oauthcli.dev/
[Mon Apr 08 19:59:24 2013] [error] [client 127.0.0.1] PHP   5. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:73, referer: http://oauthcli.dev/
[Mon Apr 08 19:59:24 2013] [error] [client 127.0.0.1] PHP   6. call_user_func_array() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauthcli.dev/
[Mon Apr 08 19:59:24 2013] [error] [client 127.0.0.1] PHP   7. LockdIn\\ControllerProvider->LockdIn\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauthcli.dev/
[Mon Apr 08 19:59:24 2013] [error] [client 127.0.0.1] PHP   8. OAuth2\\HttpFoundationBridge\\Server->getResponse() /home/philippe/dev/gitcortext/cortext-auth/server/src/LockdIn/ControllerProvider.php:20, referer: http://oauthcli.dev/
[Mon Apr 08 19:59:24 2013] [error] [client 127.0.0.1] PHP   9. OAuth2\\HttpFoundationBridge\\Server->createResponse() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/bshaffer/oauth2-server-httpfoundation-bridge/src/OAuth2/HttpFoundationBridge/Server.php:26, referer: http://oauthcli.dev/
[Mon Apr 08 20:00:05 2013] [error] [client 127.0.0.1] PHP Catchable fatal error:  Argument 1 passed to OAuth2\\HttpFoundationBridge\\Server::createResponse() must be an instance of OAuth2_Response, null given, called in /home/philippe/dev/gitcortext/cortext-auth/server/vendor/bshaffer/oauth2-server-httpfoundation-bridge/src/OAuth2/HttpFoundationBridge/Server.php on line 26 and defined in /home/philippe/dev/gitcortext/cortext-auth/server/vendor/bshaffer/oauth2-server-httpfoundation-bridge/src/OAuth2/HttpFoundationBridge/Server.php on line 29
[Mon Apr 08 20:00:05 2013] [error] [client 127.0.0.1] PHP Stack trace:
[Mon Apr 08 20:00:05 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:0
[Mon Apr 08 20:00:05 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:62
[Mon Apr 08 20:00:05 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/silex/silex/src/Silex/Application.php:481
[Mon Apr 08 20:00:05 2013] [error] [client 127.0.0.1] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/silex/silex/src/Silex/Application.php:504
[Mon Apr 08 20:00:05 2013] [error] [client 127.0.0.1] PHP   5. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:73
[Mon Apr 08 20:00:05 2013] [error] [client 127.0.0.1] PHP   6. call_user_func_array() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129
[Mon Apr 08 20:00:05 2013] [error] [client 127.0.0.1] PHP   7. LockdIn\\ControllerProvider->LockdIn\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129
[Mon Apr 08 20:00:05 2013] [error] [client 127.0.0.1] PHP   8. OAuth2\\HttpFoundationBridge\\Server->getResponse() /home/philippe/dev/gitcortext/cortext-auth/server/src/LockdIn/ControllerProvider.php:20
[Mon Apr 08 20:00:05 2013] [error] [client 127.0.0.1] PHP   9. OAuth2\\HttpFoundationBridge\\Server->createResponse() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/bshaffer/oauth2-server-httpfoundation-bridge/src/OAuth2/HttpFoundationBridge/Server.php:26
[Mon Apr 08 20:11:18 2013] [error] [client 127.0.0.1] PHP Fatal error:  Class 'Ctauth\\ControllerProvider' not found in /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php on line 52, referer: http://oauthcli.dev/
[Mon Apr 08 20:11:18 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauthcli.dev/
[Mon Apr 08 20:11:18 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:0, referer: http://oauthcli.dev/
[Mon Apr 08 20:11:19 2013] [error] [client 127.0.0.1] PHP Fatal error:  Class 'Ctauth\\ControllerProvider' not found in /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php on line 52
[Mon Apr 08 20:11:19 2013] [error] [client 127.0.0.1] PHP Stack trace:
[Mon Apr 08 20:11:19 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:0
[Tue Apr 09 16:33:14 2013] [error] [client 127.0.0.1] PHP Catchable fatal error:  Argument 1 passed to OAuth2\\HttpFoundationBridge\\Server::createResponse() must be an instance of OAuth2_Response, null given, called in /home/philippe/dev/gitcortext/cortext-auth/server/vendor/bshaffer/oauth2-server-httpfoundation-bridge/src/OAuth2/HttpFoundationBridge/Server.php on line 26 and defined in /home/philippe/dev/gitcortext/cortext-auth/server/vendor/bshaffer/oauth2-server-httpfoundation-bridge/src/OAuth2/HttpFoundationBridge/Server.php on line 29, referer: http://oauth.dev/
[Tue Apr 09 16:33:14 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauth.dev/
[Tue Apr 09 16:33:14 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:0, referer: http://oauth.dev/
[Tue Apr 09 16:33:14 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:72, referer: http://oauth.dev/
[Tue Apr 09 16:33:14 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/silex/silex/src/Silex/Application.php:481, referer: http://oauth.dev/
[Tue Apr 09 16:33:14 2013] [error] [client 127.0.0.1] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/silex/silex/src/Silex/Application.php:504, referer: http://oauth.dev/
[Tue Apr 09 16:33:14 2013] [error] [client 127.0.0.1] PHP   5. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:73, referer: http://oauth.dev/
[Tue Apr 09 16:33:14 2013] [error] [client 127.0.0.1] PHP   6. call_user_func_array() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/
[Tue Apr 09 16:33:14 2013] [error] [client 127.0.0.1] PHP   7. Ctauth\\ControllerProvider->Ctauth\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/
[Tue Apr 09 16:33:14 2013] [error] [client 127.0.0.1] PHP   8. OAuth2\\HttpFoundationBridge\\Server->getResponse() /home/philippe/dev/gitcortext/cortext-auth/server/src/Ctauth/ControllerProvider.php:20, referer: http://oauth.dev/
[Tue Apr 09 16:33:14 2013] [error] [client 127.0.0.1] PHP   9. OAuth2\\HttpFoundationBridge\\Server->createResponse() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/bshaffer/oauth2-server-httpfoundation-bridge/src/OAuth2/HttpFoundationBridge/Server.php:26, referer: http://oauth.dev/
[Tue Apr 09 16:34:05 2013] [error] [client 127.0.0.1] PHP Fatal error:  Class 'LockdIn\\ControllerProvider' not found in /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php on line 52, referer: http://oauth.dev/
[Tue Apr 09 16:34:05 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauth.dev/
[Tue Apr 09 16:34:05 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:0, referer: http://oauth.dev/
[Tue Apr 09 16:34:07 2013] [error] [client 127.0.0.1] PHP Fatal error:  Class 'LockdIn\\ControllerProvider' not found in /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php on line 52
[Tue Apr 09 16:34:07 2013] [error] [client 127.0.0.1] PHP Stack trace:
[Tue Apr 09 16:34:07 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:0
[Tue Apr 09 16:34:16 2013] [error] [client 127.0.0.1] PHP Fatal error:  Class 'LockdIn\\ControllerProvider' not found in /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php on line 52
[Tue Apr 09 16:34:16 2013] [error] [client 127.0.0.1] PHP Stack trace:
[Tue Apr 09 16:34:16 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:0
[Tue Apr 09 16:34:18 2013] [error] [client 127.0.0.1] PHP Fatal error:  Class 'LockdIn\\ControllerProvider' not found in /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php on line 52
[Tue Apr 09 16:34:18 2013] [error] [client 127.0.0.1] PHP Stack trace:
[Tue Apr 09 16:34:18 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:0
[Tue Apr 09 16:34:50 2013] [error] [client 127.0.0.1] PHP Catchable fatal error:  Argument 1 passed to OAuth2\\HttpFoundationBridge\\Server::createResponse() must be an instance of OAuth2_Response, null given, called in /home/philippe/dev/gitcortext/cortext-auth/server/vendor/bshaffer/oauth2-server-httpfoundation-bridge/src/OAuth2/HttpFoundationBridge/Server.php on line 26 and defined in /home/philippe/dev/gitcortext/cortext-auth/server/vendor/bshaffer/oauth2-server-httpfoundation-bridge/src/OAuth2/HttpFoundationBridge/Server.php on line 29, referer: http://oauth.dev/
[Tue Apr 09 16:34:50 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauth.dev/
[Tue Apr 09 16:34:50 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:0, referer: http://oauth.dev/
[Tue Apr 09 16:34:50 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:61, referer: http://oauth.dev/
[Tue Apr 09 16:34:50 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/silex/silex/src/Silex/Application.php:481, referer: http://oauth.dev/
[Tue Apr 09 16:34:50 2013] [error] [client 127.0.0.1] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/silex/silex/src/Silex/Application.php:504, referer: http://oauth.dev/
[Tue Apr 09 16:34:50 2013] [error] [client 127.0.0.1] PHP   5. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:73, referer: http://oauth.dev/
[Tue Apr 09 16:34:50 2013] [error] [client 127.0.0.1] PHP   6. call_user_func_array() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/
[Tue Apr 09 16:34:50 2013] [error] [client 127.0.0.1] PHP   7. Ctauth\\ControllerProvider->Ctauth\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/
[Tue Apr 09 16:34:50 2013] [error] [client 127.0.0.1] PHP   8. OAuth2\\HttpFoundationBridge\\Server->getResponse() /home/philippe/dev/gitcortext/cortext-auth/server/src/Ctauth/ControllerProvider.php:20, referer: http://oauth.dev/
[Tue Apr 09 16:34:50 2013] [error] [client 127.0.0.1] PHP   9. OAuth2\\HttpFoundationBridge\\Server->createResponse() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/bshaffer/oauth2-server-httpfoundation-bridge/src/OAuth2/HttpFoundationBridge/Server.php:26, referer: http://oauth.dev/
[Tue Apr 09 16:36:14 2013] [error] [client 127.0.0.1] PHP Catchable fatal error:  Argument 1 passed to OAuth2\\HttpFoundationBridge\\Server::createResponse() must be an instance of OAuth2_Response, null given, called in /home/philippe/dev/gitcortext/cortext-auth/server/vendor/bshaffer/oauth2-server-httpfoundation-bridge/src/OAuth2/HttpFoundationBridge/Server.php on line 26 and defined in /home/philippe/dev/gitcortext/cortext-auth/server/vendor/bshaffer/oauth2-server-httpfoundation-bridge/src/OAuth2/HttpFoundationBridge/Server.php on line 29, referer: http://oauth.dev/
[Tue Apr 09 16:36:14 2013] [error] [client 127.0.0.1] PHP Stack trace:, referer: http://oauth.dev/
[Tue Apr 09 16:36:14 2013] [error] [client 127.0.0.1] PHP   1. {main}() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:0, referer: http://oauth.dev/
[Tue Apr 09 16:36:14 2013] [error] [client 127.0.0.1] PHP   2. Silex\\Application->run() /home/philippe/dev/gitcortext/cortext-auth/server/web/index.php:61, referer: http://oauth.dev/
[Tue Apr 09 16:36:14 2013] [error] [client 127.0.0.1] PHP   3. Silex\\Application->handle() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/silex/silex/src/Silex/Application.php:481, referer: http://oauth.dev/
[Tue Apr 09 16:36:14 2013] [error] [client 127.0.0.1] PHP   4. Symfony\\Component\\HttpKernel\\HttpKernel->handle() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/silex/silex/src/Silex/Application.php:504, referer: http://oauth.dev/
[Tue Apr 09 16:36:14 2013] [error] [client 127.0.0.1] PHP   5. Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:73, referer: http://oauth.dev/
[Tue Apr 09 16:36:14 2013] [error] [client 127.0.0.1] PHP   6. call_user_func_array() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/
[Tue Apr 09 16:36:14 2013] [error] [client 127.0.0.1] PHP   7. Ctauth\\ControllerProvider->Ctauth\\{closure}() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:129, referer: http://oauth.dev/
[Tue Apr 09 16:36:14 2013] [error] [client 127.0.0.1] PHP   8. OAuth2\\HttpFoundationBridge\\Server->getResponse() /home/philippe/dev/gitcortext/cortext-auth/server/src/Ctauth/ControllerProvider.php:20, referer: http://oauth.dev/
[Tue Apr 09 16:36:14 2013] [error] [client 127.0.0.1] PHP   9. OAuth2\\HttpFoundationBridge\\Server->createResponse() /home/philippe/dev/gitcortext/cortext-auth/server/vendor/bshaffer/oauth2-server-httpfoundation-bridge/src/OAuth2/HttpFoundationBridge/Server.php:26, referer: http://oauth.dev/
